spring:
  activemq:
    broker-url: tcp://192.168.91.6:61616
    user: admin
    password: admin
#### ¿ªÆô·¢²¼¶©ÔÄ   
  jms: 
    pub-sub-domain: true

my_topic: springboot-topic-toov5
server:
  port: 8085
