spring:
  activemq:
    broker-url: tcp://192.168.91.6:61616
    user: admin
    password: admin
  mail:
  ##163邮件服务
    host: smtp.163.com
    ##发送邮件账号
    username: acmchangyuan@163.com
    ##授权码
    password: yugongv5
    enable:  true
    smtp:
      auth: true
    starttls:
      enable: true
      required: true
my_queue: springboot-queue-toov5
server:
  port: 8080
      

      